### ISSUE TITLE
Have detailed documentation

### ISSUE THREAD

**Issue by dashayushman** [Neural-Space/genos#2]
AC:
- Logo
- Add contributors from sourcerers (refer to hf transformers)
- Badges:
   - CI/CD Build
   - Code Coverage
   - Code Quality
- Contribution Guidelines
- Issue Guidelines + Templates
   * Bugs
   * Enhancements
   * Features
- Pull Request Template
- Code review by code owners
- Definition of Done
   * At least 2 reviews
   * Passing CI
- License
- Citation
- Usage Documentation and Examples
    * Basic and Advanced usage 
    * Multiple examples showing simple to complex instantiation strategies
- Attribution:
    * Hydra

**Comment by kushalj001** [comment]
- [ ] Logo
- [ ] Badges:
   - [x] CI/CD Build
   - [ ] Code Coverage
   - [ ] Code Quality
- [x] Contribution Guidelines
   - [x] Issue Guidelines + Templates
   - [x] Bugs
   - [x] Enhancements
- [x] Pull Request Template
- [x] Code review by code owners
- [x] Passing CI
- [x] License
- [ ] Citation
- [ ] Usage Documentation and Examples
   - [ ] Basic and Advanced usage
   - [ ] Multiple examples showing simple to complex instantiation strategies
- [x] Attribution:
- [x] Hydra
